# Generated by Django 5.1.6 on 2025-03-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycalendar',
            name='leave_days',
            field=models.DateField(),
        ),
    ]
