# Generated by Django 5.1.6 on 2025-03-06 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_salarycalendar_leave_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycalendar',
            name='leave_days',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
